### ISSUE TITLE
How to use vxlang in the mingw project？

### ISSUE THREAD

**Issue by Ptkatz** [vxlang/vxlang-page#10]

**Comment by 0a777h** [comment]
Hi, thanks for your interest in vxlang :)

You can enter the target file into vxlang.
Ex. vxlang.exe test.exe

PS.
After version 1.0.0, the packer bug has been identified and will be fixed. We apologize for the disruption.

Thank you.

**Comment by Ptkatz** [comment]
Thanks for your help ；）
