### ISSUE TITLE
The Program Faiiled To Run Debugger or memory tampering maybe be the cause 

### ISSUE THREAD

**Issue by idkhidden** [vxlang/vxlang-page#11]
![image](https://github.com/vxlang/vxlang-page/assets/91305428/62a41423-8a27-4fc4-8849-d2d2f766027e)
Randomly got this error cant pack a file
Cant Even Open Files Packed With Vxlang
FIXED HAD PROBLEM WITH WINDBG 
bcdedit -debug off

**Comment by 0a777h** [comment]
Hi, idahidden :)

By default, the debug mode setting is blocked. I recommend turning off debug mode for testing your project, or turning off anti-debugging.

Thanks :)
