### ISSUE TITLE
after obfuscation my dll working weird

### ISSUE THREAD

**Issue by fwflunky** [vxlang/vxlang-page#12]
Hello, im looking for code virtualizer and obfuscator, and planning purchase vxlang subscription. But i have issue with demo program: im developing cheat for some game, and some functions (idk why, but 90% of that functions working fine after hooking) that i hooked with minhook seems not working. For example, 
![image](https://github.com/vxlang/vxlang-page/assets/38854160/33593957-15d8-4a26-a1bd-a41a3471fcb0)

My compiler is msvc with flags /MP /Ob1, output dll going to be injected in game using my launcher
vxlang demo flags: --detect-debug --detect-patch --check-image

**Comment by fwflunky** [comment]
issue was in ob1 flag

**Comment by 0a777h** [comment]
Hi fwflunky :)

Thanks for checking out the VxLang project and the issue.

I will try to make the vxlang project better.

**Comment by fwflunky** [comment]
> Hi fwflunky :)
> 
> Thanks for checking out the VxLang project and the issue.
> 
> I will try to make the vxlang project better.

can i contact with you in telegram or etc? I don't want to open issues every time.
