### ISSUE TITLE
Protect Android x86_x64.so Crash

### ISSUE THREAD

**Issue by tangxiaodao** [vxlang/vxlang-page#14]
Protect Android x86_x64.so Crash,the so from Android xxx.apk--->lib

**Comment by 0a777h** [comment]
Hello tangxiaodao :)

This tool currently only supports Windows binaries. I developed the ELF parser, but have stopped further development on ELF until Windows binaries are more stable..

Thank you for your interest in VxLang and I apologize for not being able to help !

**Comment by tangxiaodao** [comment]
Thank you for your reply. Perhaps you can refer to the leaked VMProtect source code. I am currently repairing the ELF encryption part in the leaked source code.xD
