### ISSUE TITLE
Does it work on .Net framework console applications?

### ISSUE THREAD

**Issue by po0p** [vxlang/vxlang-page#2]
The virtualization succedes, but i cant start the console application, it exists at soon as demo messagebox is shown.

**Comment by 0a777h** [comment]
Hi, po0p :)

Thank you so much for your help! 
I have confirmed that the object settings were incorrect inside the core and have made a temporary fix.

- test: https://github.com/vxlang/vxlang-page/tree/main/bug-report/2/src
- temp-module: https://github.com/vxlang/vxlang-page/tree/main/bug-report/2/temp

**Comment by po0p** [comment]
Hey @0a777h, it indeed works. 
Tho i was not able to attach with dnspy, i could dump inital .net executable in absolutely clear way with extreme dumper :)

**Comment by po0p** [comment]
I assume for .net you just do CLR hosting and all the protection actually goes to the native host?

**Comment by 0a777h** [comment]
> I assume for .net you just do CLR hosting and all the protection actually goes to the native host?

That's right, Everything works down to the native host. Thanks for the review :)

I'll make an update !
