### ISSUE TITLE
Some suggestions.

### ISSUE THREAD

**Issue by Smellon69** [vxlang/vxlang-page#5]
So I really like it, but making it where we can customize the section header name would be really cool. aswell as maybe being able to fake other things like Themida or VMP by changing section headers and the actual protection stuff. Overall, it's a solid program and I really enjoy the beta.

**Comment by 0a777h** [comment]
> So I really like it, but making it where we can customize the section header name would be really cool. aswell as maybe being able to fake other things like Themida or VMP by changing section headers and the actual protection stuff. Overall, it's a solid program and I really enjoy the beta.

Thank you so much for trying out the vxlang beta and for your interest :)

I'll try to make it more robust with more testing (Unreal Engine and Unity game samples, various binary targets).

The ability to modify section names will be added in the next version. (I'm currently working on ELF and .NET protection).

Thank you very much :)

**Comment by Smellon69** [comment]
> > So I really like it, but making it where we can customize the section header name would be really cool. aswell as maybe being able to fake other things like Themida or VMP by changing section headers and the actual protection stuff. Overall, it's a solid program and I really enjoy the beta.
> 
> Thank you so much for trying out the vxlang beta and for your interest :)
> 
> I'll try to make it more robust with more testing (Unreal Engine and Unity game samples, various binary targets).
> 
> The ability to modify section names will be added in the next version. (I'm currently working on ELF and .NET protection).
> 
> Thank you very much :)

also one issue I discovered with x86 C++ is when you try to protect entrypoint it just won't do it and it keeps looping the same message in console

**Comment by 0a777h** [comment]
> 

I'll check it out.
Can I get a sample binary ?

**Comment by Smellon69** [comment]
I've made a simple console application in x86 that displays "Hello world" it won't even virtualize entry on this one.
[ConsoleApplication3.zip](https://github.com/vxlang/vxlang-page/files/12470051/ConsoleApplication3.zip)

**Comment by Smellon69** [comment]
btw when protecting this file it wont even run it. it just shows a console and then closes.

**Comment by 0a777h** [comment]
> I've made a simple console application in x86 that displays "Hello world" it won't even virtualize entry on this one. [ConsoleApplication3.zip](https://github.com/vxlang/vxlang-page/files/12470051/ConsoleApplication3.zip)

There was a crash during the obfuscation hash table generation process that caused an infinite loop, I will fix and update.
Thank you for your help :)

**Comment by 0a777h** [comment]
Fixed 32bit related bugs and added section renaming in the full version (Code Obfuscation or Code Virtualization section).
