### ISSUE TITLE
The code execution cannot proceed because vxlib64.dll was not found. 

### ISSUE THREAD

**Issue by soultellegend** [vxlang/vxlang-page#8]
I attempted to replicate the actions performed in the sample project located within the "src" folder. Although I successfully linked the necessary libraries, upon launching the application, it prompts me to provide the required DLL files.

**Comment by 0a777h** [comment]
When I apply the SDK and run it, it doesn't work. After applying, please check if it works after obfuscation through vxlang.

```c++
vxlang.exe sample.exe
```

**Comment by 0a777h** [comment]
> I attempted to replicate the actions performed in the sample project located within the "src" folder. Although I successfully linked the necessary libraries, upon launching the application, it prompts me to provide the required DLL files.

If you have any problems, please reopen the issue.
